# Generated by Django 5.0.6 on 2024-07-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='total_videos',
            field=models.IntegerField(default=0),
        ),
    ]
